parameters:
    matm.dataset_maker.class: MatM\Bundle\TypeAheadBundle\Services\TypeAheadDataBuilder
services:
    matm.typeahead_transformer:
        class: MatM\Bundle\TypeAheadBundle\Form\DataTransformer\TypeAheadTransformer
        arguments: ["@doctrine.orm.entity_manager"]

    matm.typeahead_type:
        class: MatM\Bundle\TypeAheadBundle\Form\Type\TypeAheadType
        arguments: ["@matm.typeahead_transformer"]
        tags:
            - { name: form.type, alias: typeahead }

    matm.dataset_maker:
        class: %matm.dataset_maker.class%
